### PR TITLE
Continuing to align with review comments to week of 7th May 2018

### PR DESCRIPTION
**Pull request by g3ysx**
Hopefully my original was synced.

If not reject the changes and I will fix up the fork and reapply the changes.

### CODE REVIEW

**Comment by agmalis** [comment]
Jouni and Stewart,

I just downloaded the xml and tried to compile it on the IETF tools site.
It fails on line 1143:

    [Editor's note: when this section is re-written a reference to <xref
target="PTI-section"/> should be included]

"PTI-section" is undefined.

Cheers,
Andy

**Comment by jounikor** [comment]
ack. i’ll check this.

**Comment by agmalis** [comment]
The missing declaration is:

<section title="Indication of the DetNet Payload Type" anchor="PTI-section">

- Stewart

**Comment by agmalis** [comment]
A bit more context


  <section title="DetNet data plane overview" anchor="sec_dt_dp">
--
     within the DetNet domain. Thus the S-label can only be used to 
identify the DetNet flow
     at the intended receiving node.
    </t>
   </section>

   <section title="Indication of the DetNet Payload Type" 
anchor="PTI-section">
    <t>
     The only nodes that needs to know the payload type of a flow are the
     DetNet ingress node and the DetNet egress nodes.
     The ingress node has to know how to process the packet it receives
     from the ingress AC, and egress edge node has to know how to
--
    <t>
     [Editor's note: quite a bit of unfinished and old text in the 
following sections.]
    </t>
    <t></t>
    <t>
     [Editor's note: when this section is re-written a reference to 
<xref target="PTI-section"/> should be included]
    </t>
    <t>
      The edge and relay node internal procedures of the PROEF are 
implementation specific.  The order

- Stewart

**Comment by jounikor** [comment]
Compiles again.

**Comment by agmalis** [comment]
Thanks! Mostly looks great. I just noticed a typo on p. 29:

   As in Section 6.2, the S-Label is used to identify a DetNet flow to
   the peer node that processes it, in this case the node addressed by
   the IP Header in Figure 14.  The S-Label is allocated from the
   receiving node?s platform label space [RFC3031].

In the last line of that paragraph, the second word should be “node’s”.
Obviously a character set error.

Cheers,
Andy

**Pull request merged**
